name: Docker clojure image with Snyk

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
    - cron: '39 2 * * 5

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Run Snyk to check image for vulnerabilities
      continue-on-error: true
      uses: snyk/actions/iac@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        image: clojure:openjdk-8-lein
        json: true
   - name: Upload result to GitHub Code Scanning
     uses: github/codeql-action/upload-sarif@v1
     with:
       name: SARIF
       path: snyk.sarif
